sudo: false
language: ruby
cache: bundler

rvm:
  - 2.4.5
  - 2.5.3
  - 2.6.1
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

# before_install: gem update --remote bundler
install:
  - gem install bundler -v 1.17.3
  - bundle install --retry=3
script:
  - bundle exec rspec
  - CODECLIMATE_REPO_TOKEN=3a6375a48b6a49b4da5a4aa32fbfce8445671f77d867c4d207ae92fc32d159ed bundle exec codeclimate-test-reporter
